---
- name: combine rbenv configuration
  set_fact:
    ranger: "{{ _rbenv|combine(rbenv, recursive=True) }}"

- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_tasks: packages.yml

