---
- name: combine rbenv configuration
  set_fact:
    ranger: "{{ _rbenv|combine(rbenv, recursive=True) }}"

- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_tasks: packages.yml

- name: install rbenv repo
  git:
    repo: "{{ rbenv.repo_source }}"
    dest: "{{ rbenv.repo_path }}"
    version: "{{ rbenv.repo_version }}"
